apiVersion: v1
kind: Service
metadata:
  name: insuretech-app-service
  labels:
    app: insuretech-app
spec:
  selector:
    app: insuretech-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
  type: NodePort