apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insuretech-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: insuretech-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s